# Generated by Django 4.2.24 on 2025-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('origin', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('summary', models.JSONField()),
                ('geojson', models.JSONField()),
                ('waypoints', models.JSONField()),
                ('stops', models.JSONField()),
                ('log_sheets', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
